### ISSUE TITLE
Keybinding doesn't work

### ISSUE THREAD

**Issue by pwFoo** [Andr3as/Codiad-CodeSettings#2]
Added default "addCursorAbove" and "addCursorBelow" with "Ctrl-Alt-UP" / "Ctrl-Alt-Down" (default values) and keybinding doesn't work also after a codiad reload.

**Comment by pwFoo** [comment]
I use wernight docker image (alpine based) mentioned in the codiad wiki and installed the extensions. Added keybindings which ignored.
- Surface Pro 4 with Dock and external displays
- Win10 OS
- Chrome 55

Which more details could help?

**Comment by pwFoo** [comment]
Strange...
Tested it again today without any problems.
So it shouldn't plugin related!

Issue should be closed. If I can reproduce it with more information I could open a new one.

Thanks!

**Comment by Andr3as** [comment]
Okay, strange. If I got some time I test the docker image.

Please reopen if required
